DOCNAME=report
OUTLINE=skeleton

skeleton:
	pdflatex ${OUTLINE}.tex

report:
	pdflatex ${DOCNAME}.tex

clean:
	rm -rf ${DOCNAME}.aux ${DOCNAME}.pdf ${DOCNAME}.log
	rm -rf ${OUTLINE}.aux ${OUTLINE}.pdf ${OUTLINE}.log
