DOCNAME=report
OUTLINE=notes
default:
	pdflatex ${DOCNAME}.tex
	pdflatex ${OUTLINE}.tex
clean:
	rm -rf ${DOCNAME}.aux ${DOCNAME}.pdf ${DOCNAME}.log
	rm -rf ${OUTLINE}.aux ${OUTLINE}.pdf ${OUTLINE}.log
